#!/usr/bin/env python3
from pathlib import Path
import json
import sqlite3
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "app/src/main/assets"
DATABASE_PATH = ASSETS / "bsb.sqlite"
READINGS_PATH = ASSETS / "curated_daily_verses.json"

REQUIRED_FILES = [
    "settings.gradle.kts",
    "build.gradle.kts",
    "gradle.properties",
    "gradle/libs.versions.toml",
    "gradlew",
    "gradlew.bat",
    "app/build.gradle.kts",
    "app/src/main/AndroidManifest.xml",
    "app/src/main/assets/bsb.sqlite",
    "app/src/main/assets/curated_daily_verses.json",
    "app/src/main/java/com/joel/minimallauncher/MainActivity.kt",
    "app/src/main/java/com/joel/minimallauncher/DeviceAdminReceiver.kt",
    "app/src/main/java/com/joel/minimallauncher/ui/LauncherApp.kt",
    "app/src/main/java/com/joel/minimallauncher/ui/LauncherViewModel.kt",
    "app/src/main/java/com/joel/minimallauncher/verse/BibleRepository.kt",
    "app/src/main/java/com/joel/minimallauncher/verse/DailyVerseRepository.kt",
]


def fail(message: str) -> None:
    raise SystemExit(message)


# Confirm all required files exist.
missing_files = [
    relative_path
    for relative_path in REQUIRED_FILES
    if not (ROOT / relative_path).is_file()
]
if missing_files:
    fail("Missing required files:\n" + "\n".join(missing_files))


# Validate all Android XML resources.
for xml_path in ROOT.glob("app/src/main/**/*.xml"):
    try:
        ET.parse(xml_path)
    except ET.ParseError as exc:
        fail(f"Malformed XML file {xml_path.relative_to(ROOT)}: {exc}")


# Validate required launcher and device-admin manifest declarations.
manifest = (ROOT / "app/src/main/AndroidManifest.xml").read_text(
    encoding="utf-8"
)
for token in (
    "android.intent.category.HOME",
    "android.intent.category.LAUNCHER",
    "android.app.device_admin",
):
    if token not in manifest:
        fail(f"Manifest is missing {token}")


# Validate the normalized BSB database generated by generate_bsb_database.py.
connection = sqlite3.connect(
    f"file:{DATABASE_PATH.as_posix()}?mode=ro",
    uri=True,
)

try:
    integrity_result = connection.execute(
        "PRAGMA integrity_check"
    ).fetchone()

    if not integrity_result or integrity_result[0] != "ok":
        value = integrity_result[0] if integrity_result else "no result"
        fail(f"SQLite integrity check failed: {value}")

    table_names = {
        row[0]
        for row in connection.execute(
            "SELECT name FROM sqlite_master WHERE type = 'table'"
        )
    }

    if "verses" not in table_names:
        fail(
            "Missing required normalized BSB database table: verses"
        )

    columns = {
        row[1]
        for row in connection.execute(
            'PRAGMA table_info("verses")'
        )
    }

    expected_columns = {
        "book_number",
        "book_name",
        "chapter",
        "verse",
        "text",
    }

    missing_columns = expected_columns - columns
    if missing_columns:
        fail(
            "verses table is missing columns: "
            + ", ".join(sorted(missing_columns))
        )

    verse_count = connection.execute(
        "SELECT COUNT(*) FROM verses"
    ).fetchone()[0]

    distinct_book_count = connection.execute(
        "SELECT COUNT(DISTINCT book_number) FROM verses"
    ).fetchone()[0]

    distinct_book_name_count = connection.execute(
        "SELECT COUNT(DISTINCT book_name) FROM verses"
    ).fetchone()[0]

    blank_text_count = connection.execute(
        """
        SELECT COUNT(*)
        FROM verses
        WHERE TRIM(COALESCE(text, '')) = ''
        """
    ).fetchone()[0]

    duplicate_reference_count = connection.execute(
        """
        SELECT COUNT(*)
        FROM (
            SELECT book_number, chapter, verse
            FROM verses
            GROUP BY book_number, chapter, verse
            HAVING COUNT(*) > 1
        )
        """
    ).fetchone()[0]

    if verse_count != 31_086:
        fail(
            "Expected exactly 31,086 normalized BSB verse records, "
            f"found {verse_count:,}"
        )

    if distinct_book_count != 66:
        fail(
            "Expected exactly 66 Bible book numbers, "
            f"found {distinct_book_count}"
        )

    if distinct_book_name_count != 66:
        fail(
            "Expected exactly 66 Bible book names, "
            f"found {distinct_book_name_count}"
        )

    if blank_text_count:
        fail(
            f"BSB database contains {blank_text_count} blank verse texts"
        )

    if duplicate_reference_count:
        fail(
            "BSB database contains "
            f"{duplicate_reference_count} duplicate normalized references"
        )

    available_references = {
        f"{book_name} {chapter}:{verse}"
        for book_name, chapter, verse in connection.execute(
            """
            SELECT book_name, chapter, verse
            FROM verses
            """
        )
    }

finally:
    connection.close()


# Validate curated Daily Verse data.
try:
    plans = json.loads(
        READINGS_PATH.read_text(encoding="utf-8")
    )
except json.JSONDecodeError as exc:
    fail(f"curated_daily_verses.json is invalid JSON: {exc}")

if plans.get("translation") != "BSB":
    fail(
        'curated_daily_verses.json must declare "translation": "BSB"'
    )

readings = plans.get("readings")
if not isinstance(readings, list):
    fail(
        'curated_daily_verses.json must contain a "readings" array'
    )

if len(readings) < 365:
    fail(
        "Expected at least 365 curated daily readings, "
        f"found {len(readings)}"
    )

main_references: list[str] = []
all_missing_references: dict[str, list[int]] = {}

for index, reading in enumerate(readings):
    if not isinstance(reading, dict):
        fail(f"Reading {index} must be a JSON object")

    main = reading.get("main")
    related = reading.get("related")
    themes = reading.get("themes")

    if not isinstance(main, str) or not main.strip():
        fail(f"Reading {index} has an invalid main reference")

    if (
        not isinstance(related, list)
        or len(related) != 3
        or not all(
            isinstance(reference, str) and reference.strip()
            for reference in related
        )
    ):
        fail(
            f"Reading {index} must contain exactly "
            "three valid related verse references"
        )

    if (
        not isinstance(themes, list)
        or not themes
        or not all(
            isinstance(theme, str) and theme.strip()
            for theme in themes
        )
    ):
        fail(
            f"Reading {index} must contain at least one valid theme"
        )

    for reference in [main, *related]:
        if reference not in available_references:
            all_missing_references.setdefault(
                reference,
                [],
            ).append(index)

    main_references.append(main)

if len(set(main_references)) != len(main_references):
    fail("Curated daily main references are not unique")

if all_missing_references:
    lines = [
        "Curated readings contain references not present in BSB:"
    ]

    for reference, indexes in sorted(
        all_missing_references.items()
    ):
        shown_indexes = indexes[:20]
        index_text = ", ".join(
            str(index)
            for index in shown_indexes
        )

        if len(indexes) > len(shown_indexes):
            index_text += (
                f", and {len(indexes) - len(shown_indexes)} more"
            )

        lines.append(
            f"- {reference}: used by reading indexes {index_text}"
        )

    lines.append(
        "Total missing unique references: "
        f"{len(all_missing_references)}"
    )

    fail("\n".join(lines))


# Validate critical Kotlin implementation markers.
source = "\n".join(
    path.read_text(encoding="utf-8")
    for path in ROOT.glob("app/src/main/java/**/*.kt")
)

for token in (
    "Screen.CHAPTER",
    "BibleRepository.chapter",
    "dpm.lockNow()",
    "Screen.DAILY_VERSE",
    '"bsb.sqlite"',
):
    if token not in source:
        fail(f"Required source feature missing: {token}")

for stale_token in (
    "King James Version",
    '"kjv.sqlite"',
    '"BSB_books"',
    '"BSB_verses"',
):
    if stale_token in source:
        fail(
            "Stale Bible implementation remains: "
            f"{stale_token}"
        )


print(f"Validated {len(REQUIRED_FILES)} required files.")
print("All Android XML resources are well formed.")
print(
    "Normalized BSB SQLite database integrity: OK "
    f"({distinct_book_count} books, {verse_count:,} verse records)."
)
print(
    f"Curated daily readings: {len(readings)} "
    "unique main references; every reference resolves locally."
)
print(
    "Full-chapter viewing and double-tap lock "
    "source checks: present."
)
